ARG DOCKER_REGISTRY=docker.m.daocloud.io
FROM ${DOCKER_REGISTRY}/library/python:3.12-slim

WORKDIR /srv/wecom
ENV PYTHONUNBUFFERED=1
ENV PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
ENV PIP_DEFAULT_TIMEOUT=120

COPY backend ./backend
RUN pip install --no-cache-dir -e ./backend
WORKDIR /srv/wecom/backend

CMD ["uvicorn", "wecom_app.main:app", "--host", "0.0.0.0", "--port", "8717"]
